name: cyp2d6_latam
version: "1.0.0"
config-version: 2

profile: cyp2d6_latam

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cyp2d6_latam:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
